version: '2.3'

#services:
#  web:
#    build: ./web
#    ports:
#      - "8000:8000"
#    environment:
#      - FLASK_APP=run.py
#      - FLASK_DEBUG=1
#    volumes:
#      - ./web/:/usr/src/app/web
#    command: "flask run --host=0.0.0.0 --port 8000"

#  postgres:
#    ports:
#      - "5432:5432"
